Autocorrect component overlapping fixed
fossasia/susper.com pull request #1380
Opened 2019-01-05 13:23 UTC by rajvaibhavdubey

Fixes #1369

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- Autocorrect component overlapping fixed

- https://pr-1380-fossasia-susper.surge.sh

![screenshot from 2019-01-05 18-40-39](https://user-images.githubusercontent.com/33062425/50724912-22f85500-111b-11e9-8f51-61c0f4b25790.png)

2019-01-05 14:11 UTC, shreyanshdwivedi approved these changes
LGTM :+1:

2019-01-05 14:59 UTC, neeraj3029 requested changes
Please remove extra lines, rest looks good 👍

2019-01-06 15:56 UTC, praveenojha33 approved these changes
LGTM :+1:

2019-01-06 16:29 UTC, sakshee-19 approved these changes

2019-01-07 15:36 UTC, subhahu123 commented
@rajvaibhavdubey 

not working when search result is zero please fix it also
![screenshot from 2019-01-07 21-01-54](https://user-images.githubusercontent.com/34541684/50776742-c2564d00-12bf-11e9-9eeb-b164fc13ac12.png)

![pr-1380-fossasia-susper surge sh_ pixel 2 xl](https://user-images.githubusercontent.com/34541684/50776825-021d3480-12c0-11e9-86a2-b696195cc304.png)

2019-01-07 15:40 UTC, subhahu123 requested changes
Do the required changes

2019-01-08 15:46 UTC, subhahu123 commented
now it is working on not found page but no for other
![pr-1380-fossasia-susper surge sh_search_query jian start 0 rows 10 mode text pixel 2 xl](https://user-images.githubusercontent.com/34541684/50841364-95bb3780-138a-11e9-8028-c7f4ca4142a2.png)
![pr-1380-fossasia-susper surge sh_search_query jian start 0 rows 10 mode text pixel 2 xl 1](https://user-images.githubusercontent.com/34541684/50841366-9653ce00-138a-11e9-873e-173028782f4c.png)

2019-01-08 15:50 UTC, subhahu123 requested changes
@rajvaibhavdubey    Do it for small screen also

2019-01-14 16:04 UTC, praveenojha33 commented
@rajvaibhavdubey What is the status of this PR?

2019-01-21 23:31 UTC, praveenojha33 requested changes
Please do the required changes !!

2026-06-10 10:55 UTC, closed without merging