Makes the navbar similar to google
fossasia/susper.com pull request #1401
Opened 2019-01-11 05:25 UTC by rajvaibhavdubey

Fixes #1398 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [x] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

- The search bar has been rounded
- The background of the navbar changed to white
- A seperate component has been created for the same because on the homepage the original search-bar is being used.

- https://pr-1401-fossasia-susper.surge.sh

2019-01-11 16:36 UTC, subhahu123 commented
i there is no need to create component for that because they are same except that now bar is round 
we can just create a ng-classs where we can use round css for result search (round bar) and one for index bar ( corner ) . i find no to create a seperate component for this ..as this is not required for just create a bar round

2019-01-11 16:39 UTC, subhahu123 commented
moreover there is  a problem with top-left corner
![screenshot-pr-1401-fossasia-susper surge sh-2019 01 11-22-07-51](https://user-images.githubusercontent.com/34541684/51047040-999ac400-15ed-11e9-9ba6-c53276b0ab83.png)

2019-01-11 17:51 UTC, shreyanshdwivedi reviewed
I also don't find any specific reason for use of new component for making the `search-bar` rounded. 
Also, I'll suggest not to use white background only for search-bar. Instead use same background color for the `search-bar` as well as `search-options-field` just like `Google`.
![screenshot_2019-01-11 susper - decentral search engine](https://user-images.githubusercontent.com/25428397/51050673-9573a400-15f7-11e9-8d9f-dee2d2cdba7d.png)

2019-01-11 18:53 UTC, rajvaibhavdubey commented
@subhahu123 @shreyanshdwivedi I created a different component because we need two types of search-bar , similar to google(rectangular on index and rounded on results page). I could'nt find a way to do the same without creating a new component. If you know one, do tell me :sweat_smile: .
@shreyanshdwivedi Will do the changes .

2019-01-13 09:05 UTC, subhahu123 requested changes
fix top left corner

2019-01-22 10:42 UTC, subhahu123 requested changes
![screenshot_2019-01-22 susper - decentral search engine](https://user-images.githubusercontent.com/34541684/51530201-6f080100-1e60-11e9-8d48-223bb8253f83.png)
still not working

2019-01-22 10:46 UTC, rajvaibhavdubey commented
@subhahu123 I have not fixed it yet, Please wait.

2019-01-22 11:12 UTC, rajvaibhavdubey commented
@shreyanshdwivedi @subhahu123 @praveenojha33 Why is the test covergae decreasing for the components I haven't made changes to like intelligence, navbar, results.

2019-01-25 17:49 UTC, praveenojha33 reviewed
@rajvaibhavdubey I think those components are connected with the components you made changes.

2019-02-19 16:39 UTC, sakshee-19 requested changes
Please do some changes.

2019-02-19 16:39 UTC, sakshee-19 commented on src/app/navbar/navbar.component.html
> +  style="background-color:white"
Move it to css file.

2019-02-19 16:39 UTC, sakshee-19 commented on src/app/search-bar-results/search-bar-results.component.css
> +
Remove extra lines.

2019-02-19 16:39 UTC, sakshee-19 commented on src/app/search-bar-results/search-bar-results.component.css
> +
Add EOF.

2019-02-19 16:39 UTC, sakshee-19 commented on src/app/search-bar-results/search-bar-results.component.html
> +
Add EOF.

2019-04-04 19:54 UTC, simsausaurabh commented
Closing due to inactivity, please follow up with latest codebase.

2019-04-04 19:54 UTC, closed without merging