Update styles.css
fossasia/susper.com pull request #1413
Opened 2019-01-15 18:19 UTC by subhahu123

Fixes #

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Added Surge preview link

#### Changes proposed in this pull request:

-

- https://pr-XXXX-fossasia-susper.surge.sh

-

2019-01-16 14:53 UTC, subhahu123 commented
@praveenojha33  @shreyanshdwivedi  @rajvaibhavdubey 
please review this

2019-01-16 16:43 UTC, rajvaibhavdubey approved these changes
@subhahu123 Check compatibility on firefox
![screenshot from 2019-01-16 22-11-36](https://user-images.githubusercontent.com/33062425/51264138-c844e000-19db-11e9-8817-13c3bc4884ac.png)
else LGTM :+1: 
[reference](https://havecamerawilltravel.com/photographer/webp-website/)

2019-01-17 12:11 UTC, rajvaibhavdubey requested changes
@subhahu123 .webp is not compatible on firefox

2019-01-17 14:02 UTC, subhahu123 commented
@rajvaibhavdubey  i will add the fallback images

2019-01-21 23:29 UTC, praveenojha33 requested changes
Changes are not working in Firefox !!

2019-01-27 17:27 UTC, subhahu123 commented
@praveenojha33  I have the requested changes 
Please review

2019-02-01 07:58 UTC, praveenojha33 requested changes
Please fix conflicts. @AakashMallik @shreyanshdwivedi Please review.

2019-02-01 08:15 UTC, subhahu123 commented
@praveenojha33  sorry but what conflicts

2019-02-01 18:47 UTC, shreyanshdwivedi reviewed
@subhahu123 Please squash your commits. The conflicts about which @praveenojha33 is talking about can be seen by you once you update your development branch and then rebase your branch (having this PR) with the dev branch. Please fix the conflicts and force push once everything is up to date :)

2019-02-08 13:51 UTC, subhahu123 commented
@praveenojha33  done with conflicts

2019-02-13 01:30 UTC, praveenojha33 commented
It still has conflicts(I think this is because of recent merged commits). Try updating your branch again.

2019-02-13 14:38 UTC, subhahu123 commented
@praveenojha33  please try now

2019-02-19 16:42 UTC, sakshee-19 reviewed
Just a minor change.

2019-02-19 16:42 UTC, sakshee-19 commented on src/app/dropdown/dropdown.component.html
> +
Remove extra lines.

2019-03-14 17:47 UTC, subhahu123 commented
@praveenojha33  @simsausaurabh  
please merge this
done with conflicts and rebasing

2026-06-10 10:55 UTC, closed without merging