Fixing  navbar susper logo
fossasia/susper.com pull request #1444
Opened 2019-01-27 18:00 UTC by subhahu123

Fixes #

#### Checklist

- [ ] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Added Surge preview link

#### Changes proposed in this pull request:

-

- https://pr-XXXX-fossasia-susper.surge.sh

-

2019-01-28 18:53 UTC, subhahu123 commented
not ready yet..

2019-02-01 09:06 UTC, Pipe-Runner commented
> not ready yet..

Put a [WIP] in the PR title if this is still a work in progress.

2019-02-19 16:48 UTC, sakshee-19 requested changes
Please also squash your commits.

2019-03-22 17:24 UTC, samagragupta reviewed
Please write the issue number.

2019-03-22 17:24 UTC, samagragupta commented on src/app/about/about.component.css
> +	margin-top: 17%;
Make proper indentation.

2019-03-27 15:12 UTC, simsausaurabh commented
Closing due to inactivity.
Please squash your commits properly and provide proper description of work done.

2019-03-27 15:12 UTC, closed without merging