Removed search bar on 404 page
fossasia/susper.com pull request #1452
Opened 2019-02-02 19:44 UTC by samagragupta

Fixes #1430 

#### Checklist

- [x] I have read the [Contribution & Best practices Guide](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia) and my PR follows them.
- [x] My branch is up-to-date with the Upstream `master` branch.
- [ ] I have added necessary documentation (if appropriate)
- [x] Added Surge preview link

#### Changes proposed in this pull request:

-Removed search bar on 404 page

- https://pr-XXXX-fossasia-susper.surge.sh
-Removed all details from .html, .css, .ts, .spec.ts

-
![404](https://user-images.githubusercontent.com/32234926/51784035-25bdf700-2169-11e9-86fb-30ff1d4eab8e.PNG)

2019-02-02 19:46 UTC, samagragupta commented
@Orbiter @mariobehling @simsausaurabh @praveenojha33

2019-02-03 05:54 UTC, subhahu123 requested changes
still this is not ready 
please check spec.ts file there is still something to remove 
@samagragupta 
Also  travis is failing because of that

2019-02-03 17:26 UTC, samagragupta commented
@subhahu123 Done the changes.

2019-02-03 19:08 UTC, subhahu123 approved these changes

2019-02-03 19:32 UTC, subhahu123 requested changes
Remove autocomplete service also

2019-02-04 01:59 UTC, samagragupta commented
@subhahu123 Done.
@simsausaurabh @praveenojha33 Please review.

2019-02-04 08:12 UTC, subhahu123 approved these changes

2019-02-04 09:58 UTC, neeraj3029 approved these changes

2019-02-09 14:09 UTC, sakshee-19 approved these changes

2019-02-09 16:48 UTC, praveenojha33 requested changes
@samagragupta I am unable to open test link for your PR.
![image](https://user-images.githubusercontent.com/25537606/52523522-43867280-2cb8-11e9-8bb2-7eba6951159c.png)
Also I do not think leaving a lot of empty space on 404 will be good idea. It will be great if few other people @AakashMallik @shreyanshdwivedi  can suggest their views on it. If you can provide a heroku link please provide that.

2019-02-10 08:21 UTC, samagragupta commented
@praveenojha33 The link is working for me.
Should I add some other image instead of that?

2019-02-13 01:22 UTC, praveenojha33 commented
@samagragupta Please add a heroku link I am unable to navigate to 404 page.
![image](https://user-images.githubusercontent.com/25537606/52679719-f32f3f00-2f5b-11e9-8349-389c8ffe0573.png)

2019-02-26 20:48 UTC, praveenojha33 commented
@samagragupta Please provide heroku link I am unable to see changes on 404 page using surge link. The image is appearing odd to me as we do not have anything in lower half of the screen. If possible make it similar to google. Something like this http://google.co.in/dnsacxklsq. You can crop the current image and put it in middle.

2019-02-27 18:02 UTC, samagragupta commented
> @samagragupta Please add a heroku link I am unable to navigate to 404 page.
> ![image](https://user-images.githubusercontent.com/25537606/52679719-f32f3f00-2f5b-11e9-8349-389c8ffe0573.png)

This is what I have made changes.
I have removed the search bar.

2019-03-08 07:04 UTC, simsausaurabh approved these changes

2019-03-22 17:31 UTC, samagragupta commented
@mariobehling Please review.

2019-03-27 15:07 UTC, simsausaurabh commented
@samagragupta Could you please deploy it on heroku and provide link to review?

2019-04-04 20:02 UTC, simsausaurabh commented
@praveenojha33 Are we good to go?

2026-06-10 10:55 UTC, closed without merging